language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq nodejs
install:
    - pip install tox
script:
    - tox -e pep8,$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
